import AnimalFood from '../Images/AnimalFood.png';
import DariyAndEggs from '../Images/DariyAndEggs.png';
import Desserts from '../Images/Desserts.png';
import DrinkAndJuice from '../Images/DrinkAndJuice.png';
import FishAndMeat from '../Images/fishAndMeat.png';
import FreshFruit from '../Images/FreshFruits.png';
import FrozenFood from '../Images/FrozenFood.png';
import YummyCandy from '../Images/YummyCandy.png';
import Vegetables from '../Images/Vegetables1.png';
import Snacks from '../Images/Snacks.png';
import OrangeJuice from '../Images/OrangeJuice.png';
import DogFood from '../Images/DogFood.png';
import Milk from '../Images/Milk.png';
import ChocoLava from '../Images/Chocolava.png';
import GreenPeas from '../Images/GreenPeas.jpeg'
import ColaCan from '../Images/ColaCan.png';
import BerrySmoothieBootle from '../Images/BerrySmoothieBottle.png';
import VanillaIceCream from '../Images/VanillaIceCream.png';
import FudgeBrowniePack from '../Images/FudgeBrowniePack.png';
const CategoryCollection = [
    {
        id: "animal-food",
        label: "Animal Food",
        image: AnimalFood,
        bgColor: "#FFCDD2",
        subtitle: "125+ Products",
        products: [
            {
                id: "dog-food-1",
                name: "Premium Dog Kibble",
                price: 19.99,
                originalPrice: 24.99,
                rating: 4.7,
                sold: "30/50",
                images: [DogFood],
                description: "Nutrient-rich kibble for active dogs.",
            },
            {
                id: "cat-food-1",
                name: "Grain-Free Cat Food",
                price: 14.99,
                originalPrice: 19.99,
                rating: 4.5,
                sold: "20/40",
                // images: [CarouselImage2],
                description: "Tasty and healthy cat food with tuna flavor.",
            },
            {
                id: "bird-seed-1",
                name: "Parrot Seed Mix",
                price: 9.99,
                originalPrice: 12.99,
                rating: 4.6,
                sold: "12/30",
                // images: [CarouselImage3],
                description: "Special seed blend for tropical birds.",
            },
        ],
    },
    {
        id: "dairy-eggs",
        label: "Dairy & Eggs",
        image: DariyAndEggs,
        bgColor: "#F8BBD0",
        subtitle: "125+ Products",
        products: [
            {
                id: "milk-1",
                name: "Organic Whole Milk",
                price: 3.99,
                originalPrice: 4.99,
                rating: 4.8,
                sold: "100/150",
                images: [Milk],
                description: "Fresh organic milk with full cream.",
            },
            {
                id: "eggs-1",
                name: "Farm Fresh Eggs (12pc)",
                price: 2.99,
                originalPrice: 3.49,
                rating: 4.7,
                sold: "90/100",
                // images: [CarouselImage2],
                description: "Cage-free large brown eggs.",
            },
            {
                id: "cheese-1",
                name: "Cheddar Cheese Block",
                price: 5.99,
                originalPrice: 7.99,
                rating: 4.9,
                sold: "40/60",
                // images: [CarouselImage3],
                description: "Rich and aged cheddar cheese.",
            },
        ],
    },
    {
        id: "desserts",
        label: "Desserts",
        image: Desserts,
        bgColor: "#E1BEE7",
        subtitle: "125+ Products",
        products: [
            {
                id: "cake-1",
                name: "Chocolate Lava Cake",
                price: 6.99,
                originalPrice: 9.99,
                rating: 4.9,
                sold: "70/100",
                images: [ChocoLava],
                description: "Warm cake with molten chocolate center.",
            },
            {
                id: "ice-cream-1",
                name: "Vanilla Ice Cream Tub",
                price: 4.49,
                originalPrice: 5.99,
                rating: 4.6,
                sold: "60/80",
                images: [VanillaIceCream],
                description: "Classic vanilla ice cream, family pack.",
            },
            {
                id: "brownie-1",
                name: "Fudge Brownie Pack (4pcs)",
                price: 5.99,
                originalPrice: 7.99,
                rating: 4.7,
                sold: "50/75",
                images: [FudgeBrowniePack],
                description: "Rich and chewy chocolate brownies.",
            },
        ],
    },
    {
        id: "frozen-food",
        label: "Frozen Food",
        image: FrozenFood,
        bgColor: "#FFECB3",
        subtitle: "125+ Products",
        products: [
            {
                id: "peas-1",
                name: "Frozen Green Peas",
                price: 2.49,
                originalPrice: 3.49,
                rating: 4.8,
                sold: "80/100",
                images: [GreenPeas],
                description: "Freshly frozen green peas.",
            },
            {
                id: "pizza-1",
                name: "Frozen Cheese Pizza",
                price: 5.99,
                originalPrice: 7.49,
                rating: 4.5,
                sold: "65/90",
                // images: [CarouselImage5],
                description: "Microwaveable cheese pizza, 12 inch.",
            },
            {
                id: "fries-1",
                name: "French Fries 1kg",
                price: 3.99,
                originalPrice: 5.49,
                rating: 4.6,
                sold: "70/100",
                // images: [CarouselImage6],
                description: "Crispy cut fries ready to fry.",
            },
        ],
    },
    {
        id: "snacks",
        label: "Snacks",
        image: Snacks,
        bgColor: "#FFAB91",
        subtitle: "125+ Products",
        products: [
            {
                id: "chips-1",
                name: "Salted Potato Chips",
                price: 1.49,
                originalPrice: 2.49,
                rating: 4.3,
                sold: "150/200",
                // images: [CarouselImage1],
                description: "Classic salty snack for all ages.",
            },
            {
                id: "nachos-1",
                name: "Spicy Nacho Chips",
                price: 2.49,
                originalPrice: 3.49,
                rating: 4.6,
                sold: "90/100",
                // images: [CarouselImage2],
                description: "Crunchy nachos with jalapeño flavor.",
            },
            {
                id: "popcorn-1",
                name: "Butter Popcorn",
                price: 1.99,
                originalPrice: 2.99,
                rating: 4.7,
                sold: "120/150",
                // images: [CarouselImage3],
                description: "Ready-to-eat buttered popcorn.",
            },
        ],
    },
    {
        id: "drinks",
        label: "Drinks",
        image: DrinkAndJuice,
        bgColor: "#D1C4E9",
        subtitle: "125+ Products",
        products: [
            {
                id: "juice-1",
                name: "Orange Juice (1L)",
                price: 2.99,
                originalPrice: 3.99,
                rating: 4.8,
                sold: "100/120",
                images: [OrangeJuice],
                description: "Freshly squeezed orange juice.",
            },
            {
                id: "cola-1",
                name: "Cola Can (330ml)",
                price: 1.49,
                originalPrice: 1.99,
                rating: 4.6,
                sold: "140/160",
                images: [ColaCan],
                description: "Classic fizzy cola drink.",
            },
            {
                id: "smoothie-1",
                name: "Berry Smoothie Bottle",
                price: 3.99,
                originalPrice: 4.99,
                rating: 4.7,
                sold: "85/100",
                images: [BerrySmoothieBootle],
                description: "Mixed berry smoothie, chilled.",
            },
        ],
    },
    {
        id: "fish",
        label: "Fish & Meat",
        image: FishAndMeat,
        bgColor: "#BBDEFB",
        subtitle: "125+ Products",
        products: [
            {
                id: "dog-food-1",
                name: "Premium Dog Food",
                price: 25.99,
                // images: [Dog1, Dog2, Dog3],
                description: "High-quality dog food made with real meat and grains.",
            }, {
                id: "chicken-1",
                name: "Chicken Breast (500g)",
                price: 5.99,
                originalPrice: 7.99,
                rating: 4.8,
                sold: "60/80",
                description: "Lean, boneless chicken breast.",
            },
            {
                id: "salmon-1",
                name: "Fresh Salmon Fillet",
                price: 9.99,
                originalPrice: 12.99,
                rating: 4.9,
                sold: "40/50",
                description: "Skinless Atlantic salmon portion.",
            },
            {
                id: "mutton-1",
                name: "Premium Mutton Curry Cut",
                price: 11.99,
                originalPrice: 14.99,
                rating: 4.6,
                sold: "30/40",
                description: "Fresh mutton, cleaned and cut.",
            },
        ],
    },
    {
        id: "fruit",
        label: "Fruits",
        image: FreshFruit,
        bgColor: "#C8E6C9",
        subtitle: "125+ Products",
        products: [
            {
                id: "apple-1",
                name: "Red Apples (1kg)",
                price: 2.99,
                originalPrice: 3.49,
                rating: 4.8,
                sold: "80/100",
                description: "Crisp and sweet red apples.",
            },
            {
                id: "banana-1",
                name: "Bananas (1 dozen)",
                price: 1.99,
                originalPrice: 2.49,
                rating: 4.7,
                sold: "100/120",
                description: "Fresh and ripe bananas.",
            },
            {
                id: "grapes-1",
                name: "Green Grapes (500g)",
                price: 2.49,
                originalPrice: 2.99,
                rating: 4.6,
                sold: "70/90",
                description: "Seedless sweet grapes.",
            },
        ],
    },
    {
        id: "yummycandy",
        label: "Yummy Candy",
        image: YummyCandy,
        bgColor: "#FFE0B2",
        subtitle: "125+ Products",
        products: [
            {
                id: "gummy-1",
                name: "Fruit Gummy Bears",
                price: 1.49,
                originalPrice: 1.99,
                rating: 4.6,
                sold: "200/250",
                description: "Soft gummy bears with fruity flavors.",
            },
            {
                id: "choco-1",
                name: "Milk Chocolate Bar",
                price: 2.49,
                originalPrice: 3.49,
                rating: 4.8,
                sold: "150/180",
                description: "Smooth milk chocolate delight.",
            },
            {
                id: "lollipop-1",
                name: "Assorted Lollipops (Pack of 10)",
                price: 1.99,
                originalPrice: 2.99,
                rating: 4.5,
                sold: "100/120",
                description: "Fun and fruity lollipop collection.",
            },
        ],
    },
    {
        id: "vegetables",
        label: "Vegetables",
        image: Vegetables,
        bgColor: "#C8E6C9",
        subtitle: "125+ Products",
        products: [
            {
                id: "carrot-1",
                name: "Fresh Carrots (1kg)",
                price: 1.49,
                originalPrice: 2.49,
                rating: 4.7,
                sold: "70/90",
                description: "Crisp and sweet orange carrots.",
            },
            {
                id: "broccoli-1",
                name: "Broccoli Florets (500g)",
                price: 2.99,
                originalPrice: 3.99,
                rating: 4.8,
                sold: "50/70",
                description: "Cleaned and cut fresh broccoli.",
            },
            {
                id: "spinach-1",
                name: "Organic Spinach (250g)",
                price: 1.99,
                originalPrice: 2.49,
                rating: 4.6,
                sold: "60/80",
                description: "Fresh baby spinach leaves.",
            },
        ],
    },

];

export default CategoryCollection;;
